In [71]:
api_key = 'IPMODP97MJ95M4PO'

In [72]:
from alpha_vantage.timeseries import TimeSeries
from alpha_vantage.techindicators import TechIndicators
import time
import pandas as pd
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.stats import linregress

In [73]:
cases = pd.read_csv('https://covid.ourworldindata.org/data/ecdc/total_cases.csv')
usa_date = pd.DataFrame({"Date": cases["date"], "World": cases["World"], "USA": cases["United States"]})
usa_date['Date'] = usa_date.Date.astype(str)
w = 0
stock_list = ['dji', 'ba', 'goog', '.INX']
def new_stock(stock_sym):
    ts = TimeSeries(key=api_key, output_format='pandas')
    ti = TechIndicators(key=api_key, output_format='pandas')
    stock_sym2, meta_data = ts.get_daily(symbol=stock_sym, outputsize = 'full')
    stock_sym3 = pd.DataFrame({"Date": stock_sym2.index, eval("stock_sym") + "_Close": stock_sym2["4. close"], eval("stock_sym") + "_Volume": stock_sym2["5. volume"] })
    stock_sym3.reset_index(drop=True, inplace=True)
    stock_sym3['Date'] = stock_sym3.Date.astype(str)
    return(stock_sym3)

for x in stock_list:
    w += 1
    print(w)
    if w == 1:
        first_frame = new_stock(x)
        time.sleep(10)
        print(first_frame)
    elif w == 2:
        all_frames = new_stock(x)
        fff = all_frames.merge(first_frame, left_on='Date', right_on='Date')
        print(fff)
        print("dig")
        time.sleep(10)
    elif w == 3:
        all_frames = new_stock(x)
        ggg = all_frames.merge(fff, left_on='Date', right_on='Date')
        print(ggg)
        time.sleep(10)
    else:
        all_frames = new_stock(x)
        hhh = all_frames.merge(ggg, left_on='Date', right_on='Date')
        iii = hhh.merge(usa_date, left_on='Date', right_on='Date')
        print(iii)
        iii.to_csv('dow_data.csv')

1
            Date   dji_Close   dji_Volume
0     2020-03-27  21636.7793  588830000.0
1     2020-03-26  22552.1699  705180000.0
2     2020-03-25  21200.5508  796320000.0
3     2020-03-24  20704.9102  799340000.0
4     2020-03-23  18591.9297  787970000.0
...          ...         ...          ...
5086  2000-01-07  11522.5596  184900000.0
5087  2000-01-06  11253.2598  176550000.0
5088  2000-01-05  11122.6504  203190000.0
5089  2000-01-04  10997.9297  178420000.0
5090  2000-01-03  11357.5098  169750000.0

[5091 rows x 3 columns]
2
            Date  ba_Close   ba_Volume   dji_Close   dji_Volume
0     2020-03-27    162.00  47729982.0  21636.7793  588830000.0
1     2020-03-26    180.55  63172068.0  22552.1699  705180000.0
2     2020-03-25    158.73  77314766.0  21200.5508  796320000.0
3     2020-03-24    127.68  42870185.0  20704.9102  799340000.0
4     2020-03-23    105.62  45885390.0  18591.9297  787970000.0
...          ...       ...         ...         ...          ...
5028  2000-03-31     37.81   4640100.0  10921.9199  179590000.0
5029  2000-03-30     38.63   3311100.0  10980.2500  214190000.0
5030  2000-03-29     37.88   2731000.0  11018.7197  199370000.0
5031  2000-03-28     38.00   5056400.0  10936.1104  177780000.0
5032  2000-03-27     37.13   2534000.0  11025.8496  184880000.0

[5033 rows x 5 columns]
dig
3
            Date  goog_Close  goog_Volume  ba_Close   ba_Volume   dji_Close  \
0     2020-03-27     1110.71    3208495.0    162.00  47729982.0  21636.7793
1     2020-03-26     1161.75    3573755.0    180.55  63172068.0  22552.1699
2     2020-03-25     1102.49    4081528.0    158.73  77314766.0  21200.5508
3     2020-03-24     1134.46    3344450.0    127.68  42870185.0  20704.9102
4     2020-03-23     1056.62    4044137.0    105.62  45885390.0  18591.9297
...          ...         ...          ...       ...         ...         ...
1507  2014-04-02      567.00     146700.0    128.31   2935200.0  16573.0000
1508  2014-04-01      567.16       7900.0    128.21   3952800.0  16532.6094
1509  2014-03-31      556.97      10800.0    125.49   2962000.0  16457.6602
1510  2014-03-28      559.99      41100.0    124.46   2863500.0  16323.0596
1511  2014-03-27      558.46      13100.0    123.21   3106000.0  16264.2305

       dji_Volume
0     588830000.0
1     705180000.0
2     796320000.0
3     799340000.0
4     787970000.0
...           ...
1507   78120000.0
1508   88010000.0
1509  104510000.0
1510   86370000.0
1511   93650000.0

[1512 rows x 7 columns]
4
          Date  .INX_Close   .INX_Volume  goog_Close  goog_Volume  ba_Close  \
0   2020-03-27   2541.4700  6.194330e+09     1110.71    3208495.0    162.00
1   2020-03-26   2630.0701  7.753160e+09     1161.75    3573755.0    180.55
2   2020-03-25   2475.5601  8.285670e+09     1102.49    4081528.0    158.73
3   2020-03-24   2447.3301  7.547350e+09     1134.46    3344450.0    127.68
4   2020-03-23   2237.3999  7.402180e+09     1056.62    4044137.0    105.62
..         ...         ...           ...         ...          ...       ...
56  2020-01-07   3237.1799  3.420380e+09     1393.34    1511693.0    337.28
57  2020-01-06   3246.2800  3.674070e+09     1394.21    1733149.0    333.74
58  2020-01-03   3234.8501  3.461290e+09     1360.66    1187006.0    332.76
59  2020-01-02   3257.8501  3.458250e+09     1367.37    1406731.0    333.32
60  2019-12-31   3230.7800  2.893810e+09     1337.02     962468.0    325.76

     ba_Volume   dji_Close   dji_Volume   World    USA
0   47729982.0  21636.7793  588830000.0  528019  85991
1   63172068.0  22552.1699  705180000.0  467929  69194
2   77314766.0  21200.5508  796320000.0  417061  55231
3   42870185.0  20704.9102  799340000.0  378113  46442
4   45885390.0  18591.9297  787970000.0  338298  35206
..         ...         ...          ...     ...    ...
56   9901768.0  28583.6797  258900000.0      59      0
57   5353250.0  28703.3809  252760000.0      59      0
58   3875835.0  28634.8809  239590000.0      44      0
59   4543965.0  28868.8008  251820000.0      27      0
60   4957776.0  28538.4395  193340000.0      27      0

[61 rows x 11 columns]

In [87]:
aapl_sma, aapl_meta_sma = ti.get_sma(symbol='AAPL')
aapl_sma.head()

                 SMA
date
2000-04-14  129.2815
2000-04-17  129.3250
2000-04-18  128.9215
2000-04-19  127.7680
2000-04-20  126.6460